### ISSUE TITLE
How to dynamically configure the content of meta tags

### ISSUE THREAD

**Issue by faronfandom** [shamscorner/vue-3-stackter#5]
Hello, I am doing a similar requirement recently. Using vue3+setup+vue-meta, I found that there is no API to refer to. I can ask you how to dynamically modify the content of the meta tag in <script setup>. thanks

**Comment by shamscorner** [comment]
```ts
<script setup>
import { useMeta } from 'vue-meta'
import { ref } from 'vue'

const newTitle = ref('')

useMeta({
    title: newTitle.value,
})

// change the newTitle here...
```

Can you try the above?
